### ISSUE TITLE
Not working for multiple tables in one migration

### ISSUE THREAD

**Issue by pedzed** [nilpahar/custom-migration#2]
I am getting this error:
```
MIGRATION STARTED
-> 5000_00_00_000000_create_foreign_keys Migration file invalid

   ErrorException  : Undefined variable: table_name
```
When I try to migrate this file: https://gist.github.com/pedzed/30e15d9177d6f4b4f23e945d8d51106e

**Comment by jbhasan** [comment]
Foreign key option is not allowed now. I will try to add this in our next version. 
-
Thanks

**Comment by jbhasan** [comment]
Now you can migrate these type of migration.
Please try with new version...

-
Thanks
