### ISSUE TITLE
Uncaught ReflectionClass

### ISSUE THREAD

**Issue by jorguerra** [nilpahar/custom-migration#4]
Hi, I am working with Laravel 5.3, I installed this library and at the beginning worked perfectly but suddenly it started to throw an exception when running either composer or php artisan which is

<code>
PHP Fatal error:  Uncaught ReflectionException: Class Sayeed\CustomMigrate\Commands\CustomMigrateCommand does not exist in /Users/jorgeguerra/proyectos/ohys/vendor/laravel/framework/src/Illuminate/Container/Container.php:749
Stack trace:
#0 /Users/jorgeguerra/proyectos/ohys/vendor/laravel/framework/src/Illuminate/Container/Container.php(749): ReflectionClass->__construct('Sayeed\\CustomMi...')
#1 /Users/jorgeguerra/proyectos/ohys/vendor/laravel/framework/src/Illuminate/Container/Container.php(644): Illuminate\Container\Container->build('Sayeed\\CustomMi...', Array)
#2 /Users/jorgeguerra/proyectos/ohys/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\Container\Container->make('Sayeed\\CustomMi...', Array)
#3 /Users/jorgeguerra/proyectos/ohys/vendor/laravel/framework/src/Illuminate/Console/Application.php(158): Illuminate\Foundation\Application->make('Sayeed\\CustomMi...')
#4 /Users/jorgeguerra/proyectos/ohys/vendor/laravel/framework/src/Illuminate/Console/Application.php(172): Illuminate\Conso in /Users/jorgeguerra/proyectos/ohys/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 749
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Uncaught ReflectionException: Class Sayeed\CustomMigrate\Commands\CustomMigrateCommand does not exist in /Users/jorgeguerra/proyectos/ohys/vendor/laravel/framework/src/Illuminate/Container/Container.php:749
Stack trace:
#0 /Users/jorgeguerra/proyectos/ohys/vendor/laravel/framework/src/Illuminate/Container/Container.php(749): ReflectionClass->__construct('Sayeed\\CustomMi...')
#1 /Users/jorgeguerra/proyectos/ohys/vendor/laravel/framework/src/Illuminate/Container/Container.php(644): Illuminate\Container\Container->build('Sayeed\\CustomMi...', Array)
#2 /Users/jorgeguerra/proyectos/ohys/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\Container\Container->make('Sayeed\\CustomMi...', Array)
#3 /Users/jorgeguerra/proyectos/ohys/vendor/laravel/framework/src/Illuminate/Console/Application.php(158): Illuminate\Foundation\Application->make('Sayeed\\CustomMi...')
#4 /Users/jorgeguerra/proyectos/ohys/vendor/laravel/framewo in /Users/jorgeguerra/proyectos/ohys/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 749
</code>

**Comment by jbhasan** [comment]
We are checking...

**Comment by jbhasan** [comment]
Solved in latest version
