### ISSUE TITLE
Doesn't work properly as it does fails when migration with different format.

### ISSUE THREAD

**Issue by asolopovas** [nilpahar/custom-migration#6]
```
 Schema::create('invoices', function(Blueprint $table) 
```
gives me this error 
2018_11_27_181049_create_invoices_table Migration file invalid

Schema::create("invoices", function(Blueprint $table) 
Schema::create("invoices", function (Blueprint $table) 

worked fine

**Comment by asolopovas** [comment]
What is the reason for closure?

**Comment by jbhasan** [comment]
Problem solved in new release.
-
Thanks
